import { config as dotenvConfig } from 'dotenv';
import * as https from 'https';
import { defineConfig } from 'orval';

dotenvConfig();

// Disable SSL certificate validation in development mode to access
// the API specification (Swagger JSON) via HTTPS with Orval.
// This allows connections to servers with self-signed or invalid
// certificates during development.
if (process.env.VITE_NODE_ENV === 'development') {
  https.globalAgent.options.rejectUnauthorized = false;
}

export default defineConfig({
  procareful: {
    input: {
      target: `${process.env.VITE_ORVAL_BASE_URL}/api/swagger-spec.json`,
    },
    output: {
      baseUrl: process.env.VITE_BASE_URL,
      workspace: './libs/common/src/api/',
      mode: 'split',
      target: `services.ts`,
      client: 'react-query',
      mock: false,
      override: {
        useNativeEnums: true,
        header: info => [
          `Generated by orval 🍺`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
          'eslint-disable',
        ],
        mutator: {
          path: 'axios.ts',
          name: 'axiosWrapper',
        },
        query: {
          useQuery: true,
        },
      },
    },
  },
});
