type BoardsType = {
  [key: number]: (number | null)[][][];
};

export const BOARD_SIZE = 9;
export const MATCHING_PAIR = 6;
export const MAX_ROTATIONS = 4;
export const MAX_TRANSFORMATIONS = 3;
export const FIRST_GROUP = [0, 1, 2];
export const LAST_GROUP = [6, 7, 8];
export const WIN_POINTS = 500;
export const ENGAGEMENT_POINTS = 50;
export const ABORTED_WITHOUT_PLAYING_POINTS = 0;
export const POLLING_INTERVAL = 15; // in seconds

export const NUMBER_OF_GROUP = 3;
export const LAST_ROW = 8;

export const boards: BoardsType = {
  1: [
    [
      [null, null, null, null, 2, 4, 8, 5, null],
      [8, null, 5, null, 7, 9, 2, 1, null],
      [2, null, 4, 8, 5, null, 9, null, 7],
      [null, null, null, 1, 4, null, null, null, null],
      [6, 9, null, 2, null, 5, null, 4, 1],
      [null, null, null, null, 3, 6, null, null, null],
      [4, null, 1, null, 6, 8, 7, null, 3],
      [null, 5, 6, 7, 1, null, 4, null, 2],
      [null, 7, 8, 4, 9, null, null, null, null],
    ],
    [
      [null, null, null, null, 2, 4, 8, 5, null],
      [8, null, 5, null, 7, 9, 2, 1, null],
      [2, null, 4, 8, 5, null, 9, null, 7],
      [null, null, null, 1, 4, null, null, null, null],
      [6, 9, null, 2, null, 5, null, 4, 1],
      [null, null, null, null, 3, 6, null, null, null],
      [4, null, 1, null, 6, 8, 7, null, 3],
      [null, 5, 6, 7, 1, null, 4, null, 2],
      [null, 7, 8, 4, 9, null, null, null, null],
    ],
    [
      [2, 1, null, 7, 3, null, 6, null, 8],
      [null, null, 6, null, null, 2, 3, 5, null],
      [5, null, 3, 6, 9, 8, 7, null, 2],
      [null, 6, null, 2, null, 9, 4, null, null],
      [null, null, 2, null, null, null, 1, null, null],
      [null, null, 5, 3, null, 1, null, 8, null],
      [6, null, 1, 9, 2, 7, 8, null, 4],
      [null, 8, 4, 5, null, null, 9, null, null],
      [9, null, 7, null, 8, 3, null, 6, 1],
    ],
    // free puzzles 1
    [
      [null, null, 6, null, null, null, 5, null, 8],
      [1, null, 2, 3, 8, null, null, null, 4],
      [null, null, null, 2, null, null, 1, 9, null],
      [null, null, null, null, 6, 3, null, 4, 5],
      [null, 6, 3, 4, null, 5, 8, 7, null],
      [5, 4, null, 9, 2, null, null, null, null],
      [null, 8, 7, null, null, 4, null, null, null],
      [2, null, null, null, 9, 8, 4, null, 7],
      [4, null, 9, null, null, null, 3, null, null],
    ],
    // free puzzles 2
    [
      [null, null, 3, 5, 7, null, 2, null, null],
      [2, 9, null, 1, null, 3, null, null, 6],
      [null, null, null, null, null, 4, 1, 9, null],
      [null, 8, 2, null, 3, null, null, 1, 7],
      [null, null, null, 7, null, 8, null, null, null],
      [9, 1, null, null, 4, null, 3, 6, null],
      [null, 2, 1, 4, null, null, null, null, null],
      [7, null, null, 8, null, 1, null, 2, 5],
      [null, null, 5, null, 9, 2, 6, null, null],
    ],
    // free puzzles 3
    [
      [null, null, 3, 1, null, 5, null, 7, null],
      [null, null, 2, null, 9, 7, 8, null, null],
      [null, 5, null, null, 8, 4, 9, null, 2],
      [null, 4, null, 2, null, null, 3, null, null],
      [null, 2, null, 5, null, 9, null, 4, null],
      [null, null, 9, null, null, 3, null, 1, null],
      [2, null, 4, 7, 5, null, null, 8, null],
      [null, null, 6, 4, 1, null, 5, null, null],
      [null, 1, null, 9, null, 8, 6, null, null],
    ],
    // free puzzles 4
    [
      [null, null, null, 7, null, 1, null, null, null],
      [7, 3, null, null, 9, null, null, null, 2],
      [5, 6, 1, null, null, null, 4, 9, null],
      [4, 7, 2, 3, 1, 8, null, null, null],
      [null, null, null, 5, null, 9, null, null, null],
      [null, null, null, 4, 6, 7, 2, 8, 3],
      [null, 4, 6, null, null, null, 1, 5, 9],
      [2, null, null, null, 3, null, null, 7, 4],
      [null, null, null, 1, null, 5, null, null, null],
    ],
    // free puzzles 5
    [
      [null, 7, 2, 8, null, null, null, null, 3],
      [null, 3, null, null, null, 9, null, 1, null],
      [9, null, 1, 5, null, 2, 7, null, null],
      [6, 2, null, 9, null, null, 5, null, null],
      [1, 5, null, null, null, null, null, 3, 9],
      [null, null, 9, null, null, 5, null, 6, 2],
      [null, null, 7, 4, null, 6, 3, null, 8],
      [null, 4, null, 7, null, null, null, 2, null],
      [3, null, null, null, null, 8, 4, 7, null],
    ],
    // free puzzles 6
    [
      [null, null, null, 7, 3, 1, 9, 5, 8],
      [null, null, null, null, 4, null, 1, 6, null],
      [null, null, 9, 8, 6, null, 4, null, null],
      [5, null, null, null, null, 3, null, 7, 1],
      [4, null, null, null, null, null, null, null, 5],
      [6, 9, null, 5, null, null, null, null, 4],
      [null, null, 6, null, 1, 7, 8, null, null],
      [null, 4, 2, null, 5, null, null, null, null],
      [8, 1, 7, 9, 2, 4, null, null, null],
    ],
    // free puzzles 7
    [
      [8, null, null, null, 2, null, 9, 5, 7],
      [null, null, 3, null, null, null, null, 1, 8],
      [null, 7, 9, null, 5, 8, null, 3, 4],
      [null, null, null, null, null, 6, 7, 8, null],
      [null, 8, null, null, null, null, null, 9, null],
      [null, 1, 5, 7, null, null, null, null, null],
      [7, 3, null, 5, 6, null, 8, 4, null],
      [2, 5, null, null, null, null, 3, null, null],
      [9, 6, 8, null, 3, null, null, null, 1],
    ],
    // free puzzles 8
    [
      [null, null, 6, 2, null, 5, 9, null, 8],
      [null, null, null, 6, null, 9, null, 1, null],
      [9, null, 4, null, null, null, null, 5, 6],
      [null, 8, null, 4, 5, 7, 1, null, null],
      [null, null, 9, null, null, null, 5, null, null],
      [null, null, 7, 9, 1, 2, null, 4, null],
      [6, 4, null, null, null, null, 2, null, 1],
      [null, 9, null, 1, null, 4, null, null, null],
      [2, null, 1, 8, null, 6, 7, null, null],
    ],
    // free puzzles 9
    [
      [null, null, 5, 2, null, null, null, null, 9],
      [null, 6, null, null, 3, null, null, 5, 2],
      [null, null, null, 5, null, null, 7, 1, null],
      [null, 7, 3, null, 1, null, 2, 6, 4],
      [null, 1, null, 4, null, 6, null, 7, null],
      [4, 9, 6, null, 7, null, 1, 8, null],
      [null, 2, 4, null, null, 1, null, null, null],
      [7, 3, null, null, 4, null, null, 2, null],
      [8, null, null, null, null, 3, 4, null, null],
    ],
    // free puzzles 1null
    [
      [null, null, null, null, null, 1, 7, null, null],
      [6, 5, 7, 2, null, 4, null, 3, null],
      [null, null, null, null, 7, null, null, 4, null],
      [7, null, 6, 9, null, 8, 3, 5, 4],
      [1, null, null, null, null, null, null, null, 2],
      [3, 4, 5, 7, null, 2, 9, null, 8],
      [null, 9, null, null, 2, null, null, null, null],
      [null, 6, null, 4, null, 9, 2, 8, 7],
      [null, null, 4, 5, null, null, null, null, null],
    ],
  ],
  2: [
    [
      [null, 4, null, null, null, 6, 3, 8, null],
      [1, null, 8, null, null, 3, 7, null, 2],
      [null, null, null, null, null, 8, null, 4, null],
      [null, null, null, 8, null, 5, 4, null, 9],
      [null, null, null, null, 2, null, null, null, null],
      [8, null, 5, 4, null, 1, null, null, null],
      [null, 3, null, 7, null, null, null, null, null],
      [2, null, 9, 1, null, null, 6, null, 7],
      [null, 1, 6, 3, null, null, null, 5, null],
    ],
    [
      [null, 4, null, null, null, 6, 3, 8, null],
      [1, null, 8, null, null, 3, 7, null, 2],
      [null, null, null, null, null, 8, null, 4, null],
      [null, null, null, 8, null, 5, 4, null, 9],
      [null, null, null, null, 2, null, null, null, null],
      [8, null, 5, 4, null, 1, null, null, null],
      [null, 3, null, 7, null, null, null, null, null],
      [2, null, 9, 1, null, null, 6, null, 7],
      [null, 1, 6, 3, null, null, null, 5, null],
    ],
    [
      [null, null, null, null, null, 6, null, null, 3],
      [null, 3, null, null, null, null, 9, 2, null],
      [null, null, 4, 3, null, 1, null, 8, null],
      [null, null, 1, 4, null, 5, null, null, 2],
      [null, 4, null, null, null, null, null, 5, null],
      [8, null, null, 6, null, 3, 1, null, null],
      [null, 6, null, 5, null, 7, 4, null, null],
      [null, 1, 5, null, null, null, null, 9, null],
      [4, null, null, 9, null, null, null, null, null],
    ],
    // free puzzles 1
    [
      [null, 4, null, null, 2, null, 8, 6, 5],
      [7, null, null, 6, null, 8, null, null, null],
      [1, null, null, null, null, 4, 7, null, 2],
      [null, 1, 8, 7, 4, null, null, null, null],
      [null, null, 5, 2, null, 9, 6, null, null],
      [null, null, null, null, 8, 6, 1, 5, null],
      [9, null, 1, 5, null, null, null, null, 6],
      [null, null, null, 8, null, 2, null, null, 7],
      [8, 7, 3, null, 6, null, null, 2, null],
    ],
    // free puzzles 2
    [
      [9, null, 6, null, null, 1, null, 4, null],
      [7, null, 1, 2, 9, null, null, 6, null],
      [4, null, 2, 8, null, 6, 3, null, null],
      [null, null, null, null, 2, null, 9, 8, null],
      [6, null, null, null, null, null, null, null, 2],
      [null, 9, 4, null, 8, null, null, null, null],
      [null, null, 3, 7, null, 8, 4, null, 9],
      [null, 4, null, null, 1, 3, 7, null, 6],
      [null, 6, null, 9, null, null, 1, null, 8],
    ],
    // free puzzles 3
    [
      [5, null, 8, null, null, null, null, 6, null],
      [null, 4, 2, null, null, 8, null, null, 3],
      [6, null, 3, null, 4, 9, null, null, 7],
      [8, null, 9, null, 3, null, null, null, null],
      [3, 7, null, 2, null, 1, null, 4, 8],
      [null, null, null, null, 8, null, 3, null, 2],
      [2, null, null, 1, 5, null, 4, null, 9],
      [1, null, null, 4, null, null, 2, 5, null],
      [null, 5, null, null, null, null, 7, null, 1],
    ],
    // free puzzles 4
    [
      [3, null, 6, null, null, 7, null, null, 8],
      [null, 2, null, null, null, null, null, null, 4],
      [null, 5, null, null, null, 1, 7, null, null],
      [null, null, null, 8, null, 6, null, 3, null],
      [8, 3, null, null, null, null, null, 5, 9],
      [null, 6, null, 7, null, 5, null, null, null],
      [null, null, 3, 4, null, null, null, 7, null],
      [6, null, null, null, null, null, null, 4, null],
      [1, null, null, 6, null, null, 2, null, 3],
    ],
    // free puzzles 5
    [
      [null, 9, null, 1, 6, null, null, null, 5],
      [null, 7, 1, null, null, null, null, null, 6],
      [null, null, 6, null, 9, null, null, 2, null],
      [8, 4, null, 2, 3, 5, null, null, 9],
      [null, null, 9, 4, null, 6, 2, null, null],
      [5, null, null, 7, 1, 9, null, 3, 8],
      [null, 1, null, null, 4, null, 9, null, null],
      [9, null, null, null, null, null, 3, 7, null],
      [6, null, null, null, 7, 3, null, 8, null],
    ],
    // free puzzles 6
    [
      [6, null, null, 5, null, null, null, null, null],
      [null, null, null, null, 4, 9, 1, null, null],
      [null, 8, 9, null, null, null, null, null, 5],
      [8, null, 1, 2, 5, null, null, null, 9],
      [null, 4, null, 6, null, 3, null, 5, null],
      [5, null, null, null, 9, 1, 8, null, 2],
      [7, null, null, null, null, null, 9, 1, null],
      [null, null, 8, 4, 1, null, null, null, null],
      [null, null, null, null, null, 5, null, null, 6],
    ],
    // free puzzles 7
    [
      [1, 9, null, null, null, null, 4, null, null],
      [null, null, 8, 4, null, 6, null, null, 1],
      [4, null, 6, 2, 5, null, 3, 8, null],
      [5, null, null, 3, null, null, 1, 9, null],
      [null, null, 9, null, null, null, 2, null, null],
      [null, 3, 4, null, null, 8, null, null, 5],
      [null, 4, 2, null, 3, 5, 8, null, 7],
      [6, null, null, 7, null, 4, 9, null, null],
      [null, null, 3, null, null, null, null, 4, 2],
    ],
    // free puzzles 8
    [
      [null, null, 8, null, 7, null, null, null, null],
      [null, 9, 4, null, null, 6, 3, null, null],
      [5, null, 6, 3, null, 9, 2, 8, null],
      [null, null, 5, 7, 2, 1, null, 6, 3],
      [null, null, null, null, null, null, null, null, null],
      [7, 1, null, 9, 6, 5, 8, null, null],
      [null, 6, 1, 2, null, 8, 7, null, 9],
      [null, null, 2, 1, null, null, 6, 3, null],
      [null, null, null, null, 3, null, 1, null, null],
    ],
    // free puzzles 9
    [
      [1, null, 5, null, null, null, 8, null, null],
      [null, 3, 9, 8, 2, null, null, null, null],
      [null, 7, 8, null, null, 9, null, 4, 3],
      [8, null, 6, null, 3, null, null, 9, 1],
      [null, 4, null, null, null, null, null, 3, null],
      [7, 9, null, null, 1, null, 6, null, 8],
      [6, 5, null, 3, null, null, 1, 8, null],
      [null, null, null, null, 5, 8, 9, 6, null],
      [null, null, 2, null, null, null, 3, null, 5],
    ],
    // free puzzles 1null
    [
      [null, null, null, null, 3, null, 8, 7, 1],
      [null, null, null, 1, null, null, 9, 4, 3],
      [null, null, null, 4, null, null, null, null, 2],
      [null, 7, 3, null, 1, null, null, null, 4],
      [6, null, 5, null, null, null, 7, null, 8],
      [4, null, null, null, 5, null, 1, 3, null],
      [1, null, null, null, null, 7, null, null, null],
      [8, 3, 9, null, null, 4, null, null, null],
      [7, 5, 4, null, 2, null, null, null, null],
    ],
  ],
  3: [
    [
      [null, null, null, null, 8, null, 6, 2, null],
      [null, null, 2, 4, null, null, null, 9, null],
      [null, null, 4, null, null, 6, 5, null, null],
      [null, null, null, null, null, null, null, 4, 7],
      [null, null, null, 3, 2, 9, null, null, null],
      [1, 3, null, null, null, null, null, null, null],
      [null, null, 3, 5, null, null, 2, null, null],
      [null, 9, null, null, null, 3, 1, null, null],
      [null, 5, 7, null, 1, null, null, null, null],
    ],
    [
      [null, null, null, null, null, 9, null, 2, null],
      [null, null, null, null, 2, null, 5, null, 9],
      [9, null, null, 8, null, 4, null, null, null],
      [null, 4, null, 3, null, 7, 2, null, null],
      [5, null, 8, null, null, null, 1, null, 6],
      [null, null, 7, 1, null, 8, null, 4, null],
      [null, null, null, 2, null, 3, null, null, 1],
      [8, null, 5, null, 4, null, null, null, null],
      [null, 6, null, 9, null, null, null, null, null],
    ],
    //free puzzles 1
    [
      [null, null, null, 5, null, 7, null, null, null],
      [null, 4, null, 2, 6, 3, null, null, null],
      [1, null, 7, 4, null, null, null, null, null],
      [3, 6, null, null, null, null, null, 4, 5],
      [null, null, 2, null, 5, null, 7, null, null],
      [7, 9, null, null, null, null, null, 6, 2],
      [null, null, null, null, null, 9, 4, null, 1],
      [null, null, null, 1, 3, 4, null, 9, null],
      [null, null, null, 6, null, 5, null, null, null],
    ],
    //free puzzles 2
    [
      [3, null, null, null, null, 7, null, 1, null],
      [null, 4, null, 5, 2, null, null, null, null],
      [7, null, 9, 4, null, null, null, null, null],
      [1, null, 2, null, null, null, null, null, null],
      [null, null, 7, 9, null, 6, 8, null, null],
      [null, null, null, null, null, null, 3, null, 7],
      [null, null, null, null, null, 9, 2, null, 6],
      [null, null, null, null, 7, 4, null, 3, null],
      [null, 6, null, 2, null, null, null, null, 4],
    ],
    //free puzzles 3
    [
      [null, 8, null, 6, null, null, null, 1, null],
      [null, null, null, null, null, 8, 2, 5, 6],
      [null, null, 1, null, null, null, null, null, null],
      [null, null, null, 9, null, 4, 6, null, 3],
      [null, null, 9, null, 7, null, 5, null, null],
      [4, null, 7, 5, null, 2, null, null, null],
      [null, null, null, null, null, null, 8, null, null],
      [7, 1, 3, 4, null, null, null, null, null],
      [null, 5, null, null, null, 9, null, 3, null],
    ],
    //free puzzles 4
    [
      [null, 7, 9, null, 5, null, null, null, null],
      [null, null, 5, null, null, 4, null, 1, null],
      [null, 4, 2, null, 7, 6, 8, null, null],
      [null, null, 6, null, null, 8, null, null, 4],
      [null, 2, null, null, null, null, null, 6, null],
      [7, null, null, 6, null, null, 1, null, null],
      [null, null, 1, 7, 8, null, 4, 2, null],
      [null, 3, null, 1, null, null, 6, null, null],
      [null, null, null, null, 6, null, 7, 5, null],
    ],
    //free puzzles 5
    [
      [null, null, null, null, 9, null, 2, null, null],
      [3, 6, null, null, null, null, null, 5, 7],
      [7, 1, null, null, null, null, 9, null, null],
      [null, 4, null, null, 5, 3, null, null, 8],
      [null, null, null, null, 1, null, null, null, null],
      [9, null, null, 2, 4, null, null, 1, null],
      [null, null, 4, null, null, null, null, 7, 6],
      [6, 8, null, null, null, null, null, 4, 2],
      [null, null, 7, null, 2, null, null, null, null],
    ],
    //free puzzles 6
    [
      [null, null, 6, null, 5, null, null, null, 9],
      [null, null, 7, null, null, 2, null, 8, null],
      [null, null, null, null, 3, null, 1, 7, 5],
      [null, null, null, 6, null, null, 8, null, 2],
      [null, 6, null, null, null, null, null, 3, null],
      [7, null, 9, null, null, 3, null, null, null],
      [6, 9, 3, null, 2, null, null, null, null],
      [null, 4, null, 9, null, null, 7, null, null],
      [8, null, null, null, 6, null, 9, null, null],
    ],
    //free puzzles 7
    [
      [2, null, 7, 1, null, null, 4, null, 3],
      [null, null, null, null, null, null, 8, null, null],
      [null, 8, null, 4, null, null, 5, null, null],
      [null, 6, 8, null, 4, null, null, null, null],
      [null, null, null, 3, null, 9, null, null, null],
      [null, null, null, null, 6, null, 7, 1, null],
      [null, null, 1, null, null, 6, null, 5, null],
      [null, null, 2, null, null, null, null, null, null],
      [9, null, 5, null, null, 2, 6, null, 7],
    ],
    //free puzzles 8
    [
      [4, 1, null, null, null, null, 8, null, 9],
      [null, 5, 3, 4, null, null, null, null, null],
      [null, null, null, null, 1, 3, null, null, null],
      [null, null, null, null, null, 4, null, 8, null],
      [null, null, 1, null, 2, null, 7, null, null],
      [null, 3, null, 6, null, null, null, null, null],
      [null, null, null, 2, 7, null, null, null, null],
      [null, null, null, null, null, 6, 3, 5, null],
      [9, null, 7, null, null, null, null, 4, 8],
    ],
    //free puzzles 9
    [
      [null, 1, null, 4, null, null, 2, null, null],
      [5, null, null, null, 9, 3, 1, null, null],
      [null, null, null, null, null, null, null, 5, 6],
      [9, null, 3, null, null, null, null, null, null],
      [null, null, null, 6, 8, 9, null, null, null],
      [null, null, null, null, null, null, 4, null, 7],
      [7, 5, null, null, null, null, null, null, null],
      [null, null, 8, 7, 6, null, null, null, 1],
      [null, null, 9, null, null, 1, null, 4, null],
    ],
    //free puzzles 1null
    [
      [null, null, null, null, null, 5, null, 4, null],
      [null, 8, null, null, null, null, 5, null, 6],
      [null, null, null, null, 9, 7, 1, 3, null],
      [4, null, null, null, 8, 9, 7, null, null],
      [null, null, 5, null, 1, null, 4, null, null],
      [null, null, 1, 4, 5, null, null, null, 3],
      [null, 7, 8, 5, 2, null, null, null, null],
      [2, null, 3, null, null, null, null, 8, null],
      [null, 4, null, 9, null, null, null, null, null],
    ],
  ],
  4: [
    [
      [7, null, null, 5, null, 1, null, null, 4],
      [null, null, 8, null, null, null, null, null, null],
      [9, null, 2, null, 8, null, 5, 7, null],
      [null, null, 1, null, null, 8, null, null, null],
      [6, null, null, null, 9, null, null, null, 8],
      [null, null, null, 4, null, null, 6, null, null],
      [null, 6, 7, null, 4, null, 2, null, 9],
      [null, null, null, null, null, null, 4, null, null],
      [4, null, null, 8, null, 6, null, null, 5],
    ],
    [
      [7, null, null, 5, null, 1, null, null, 4],
      [null, null, 8, null, null, null, null, null, null],
      [9, null, 2, null, 8, null, 5, 7, null],
      [null, null, 1, null, null, 8, null, null, null],
      [6, null, null, null, 9, null, null, null, 8],
      [null, null, null, 4, null, null, 6, null, null],
      [null, 6, 7, null, 4, null, 2, null, 9],
      [null, null, null, null, null, null, 4, null, null],
      [4, null, null, 8, null, 6, null, null, 5],
    ],
    [
      [2, 3, null, 5, 1, null, null, null, 6],
      [null, 9, null, null, null, null, null, null, null],
      [null, null, 6, 7, null, null, null, null, null],
      [8, 2, null, null, null, 4, null, 3, null],
      [null, null, 9, null, 8, null, 5, null, null],
      [null, 7, null, 1, null, null, null, 2, 8],
      [null, null, null, null, null, 1, 8, null, null],
      [null, null, null, null, null, null, null, 7, null],
      [7, null, null, null, 3, 6, null, 4, 1],
    ],
    // free puzzles 1
    [
      [null, null, null, null, null, 2, null, null, 4],
      [2, null, 5, null, null, 6, 8, null, 7],
      [null, 1, null, 5, null, null, null, null, null],
      [null, 6, 2, null, 3, null, null, null, null],
      [7, null, 8, null, null, null, 6, null, 5],
      [null, null, null, null, 6, null, 4, 2, null],
      [null, null, null, null, null, 7, null, 8, null],
      [4, null, 1, 6, null, null, 9, null, 2],
      [9, null, null, 2, null, null, null, null, null],
    ],
    // free puzzles 2
    [
      [null, 9, null, null, 4, null, null, null, 7],
      [null, 2, null, 5, null, null, null, 9, null],
      [null, null, 6, 9, null, 7, null, null, null],
      [8, null, null, 7, null, null, null, null, null],
      [7, null, null, null, 8, null, null, null, 4],
      [null, null, null, null, null, 3, null, null, 1],
      [null, null, null, 8, null, 9, 5, null, null],
      [null, 6, null, null, null, 5, null, 3, null],
      [5, null, null, null, 1, null, null, 2, null],
    ],
    // free puzzles 3
    [
      [8, null, null, null, null, null, 7, null, 5],
      [null, 9, 7, null, null, 5, null, 2, null],
      [null, null, 5, 6, null, null, null, 4, null],
      [null, null, 6, null, null, 1, null, null, 9],
      [null, null, null, 7, 8, 4, null, null, null],
      [1, null, null, 2, null, null, 5, null, null],
      [null, 3, null, null, null, 7, 8, null, null],
      [null, 4, null, 1, null, null, 2, 5, null],
      [5, null, 1, null, null, null, null, null, 4],
    ],
    // free puzzles 4
    [
      [9, 1, null, null, null, 5, null, null, 4],
      [null, null, null, 7, null, null, null, null, null],
      [null, null, 7, null, 8, null, 3, 9, 2],
      [null, 8, null, null, 6, null, 4, 3, null],
      [1, null, null, null, null, null, null, null, 5],
      [null, 3, 6, null, 5, null, null, 2, null],
      [8, 5, 9, null, 3, null, 7, null, null],
      [null, null, null, null, null, 7, null, null, null],
      [2, null, null, 8, null, null, null, 5, 3],
    ],
    // free puzzles 5
    [
      [8, null, 2, null, 5, null, 1, 6, null],
      [3, null, null, null, null, 7, null, null, 8],
      [6, 4, null, null, null, 8, null, 7, null],
      [null, 9, null, null, 4, null, null, null, null],
      [null, 6, null, null, null, null, null, 3, null],
      [null, null, null, null, 7, null, null, 9, null],
      [null, 8, null, 7, null, null, null, 1, 2],
      [7, null, null, 8, null, null, null, null, 5],
      [null, 2, 6, null, 1, null, 9, null, 7],
    ],
    // free puzzles 6
    [
      [null, 1, 4, null, null, null, 9, null, null],
      [null, 3, null, null, null, null, 2, null, 6],
      [null, null, null, 9, 1, null, null, 4, null],
      [null, 7, 5, 3, null, null, 6, null, null],
      [8, null, null, null, 4, null, null, null, 5],
      [null, null, 3, null, null, 5, 7, 8, null],
      [null, 6, null, null, 8, 9, null, null, null],
      [7, null, 1, null, null, null, null, 6, null],
      [null, null, 9, null, null, null, 8, 7, null],
    ],
    // free puzzles 7
    [
      [null, null, null, null, 7, null, null, 9, null],
      [null, 5, 2, null, null, null, null, 6, null],
      [null, null, null, null, null, 5, 8, 1, 7],
      [null, 7, null, null, 3, 2, null, null, 8],
      [null, null, 1, null, 8, null, 9, null, null],
      [4, null, null, 7, 5, null, null, 2, null],
      [6, 1, 5, 3, null, null, null, null, null],
      [null, 9, null, null, null, null, 6, 3, null],
      [null, 3, null, null, 4, null, null, null, null],
    ],
    // free puzzles 8
    [
      [null, 1, null, 7, null, null, null, null, null],
      [3, null, null, 2, null, null, null, 8, null],
      [null, null, 9, null, 8, 4, null, 5, null],
      [null, 3, 5, null, null, null, null, null, 8],
      [1, null, 8, null, null, null, 3, null, 6],
      [7, null, null, null, null, null, 5, 1, null],
      [null, 9, null, 8, 4, null, 2, null, null],
      [null, 2, null, null, null, 7, null, null, 4],
      [null, null, null, null, null, 5, null, 9, null],
    ],
    // free puzzles 9
    [
      [2, null, null, 7, null, null, null, null, null],
      [null, null, null, null, null, null, null, 9, 2],
      [null, null, 6, null, null, 3, null, 4, null],
      [null, null, null, 9, null, 5, null, 3, 8],
      [null, null, 4, null, null, null, 9, null, null],
      [9, 3, null, 2, null, 4, null, null, null],
      [null, 4, null, 5, null, null, 3, null, null],
      [6, 7, null, null, null, null, null, null, null],
      [null, null, null, null, null, 1, null, null, 6],
    ],
    // free puzzles 1null
    [
      [null, null, null, 3, null, null, null, 9, 5],
      [null, 5, null, null, null, null, 7, null, 2],
      [null, null, null, 5, null, null, 1, 8, null],
      [9, null, null, 2, 5, null, 3, 1, null],
      [null, null, null, null, 9, null, null, null, null],
      [null, 3, 7, null, 8, 6, null, null, 9],
      [null, 6, 1, null, null, 5, null, null, null],
      [2, null, 3, null, null, null, null, 4, null],
      [4, 7, null, null, null, 1, null, null, null],
    ],
  ],
  5: [
    [
      [null, null, 6, 7, null, null, null, null, 4],
      [null, null, 8, null, null, 3, null, null, null],
      [null, 3, null, 8, null, null, 1, null, null],
      [2, null, null, 4, 6, null, null, 5, null],
      [null, null, null, null, 1, null, null, null, null],
      [null, 5, null, null, 7, 2, null, null, 9],
      [null, null, 9, null, null, 4, null, 6, null],
      [null, null, null, 2, null, null, 5, null, null],
      [3, null, null, null, null, 6, 7, null, null],
    ],
    [
      [null, null, 6, 7, null, null, null, null, 4],
      [null, null, 8, null, null, 3, null, null, null],
      [null, 3, null, 8, null, null, 1, null, null],
      [2, null, null, 4, 6, null, null, 5, null],
      [null, null, null, null, 1, null, null, null, null],
      [null, 5, null, null, 7, 2, null, null, 9],
      [null, null, 9, null, null, 4, null, 6, null],
      [null, null, null, 2, null, null, 5, null, null],
      [3, null, null, null, null, 6, 7, null, null],
    ],
    [
      [8, null, null, null, 1, null, null, null, 3],
      [null, 3, null, null, null, null, null, 2, null],
      [null, null, 7, null, null, 2, null, null, 8],
      [null, null, null, null, 3, 8, null, null, 6],
      [null, null, 8, null, 7, null, 4, null, null],
      [4, null, null, 1, 6, null, null, null, null],
      [6, null, null, 5, null, null, 1, null, null],
      [null, 9, null, null, null, null, null, 5, null],
      [1, null, null, null, 9, null, null, null, 2],
    ],
    // free puzzles 1
    [
      [null, null, 7, 4, null, null, null, null, null],
      [null, null, null, null, 2, 9, null, null, 6],
      [4, null, 3, null, null, null, null, 9, 2],
      [null, null, 2, 1, 4, null, null, null, null],
      [3, null, null, 8, null, 2, null, null, 5],
      [null, null, null, null, 9, 6, 1, null, null],
      [5, 9, null, null, null, null, 3, null, 1],
      [2, null, null, 9, 5, null, null, null, null],
      [null, null, null, null, null, 4, 2, null, null],
    ],
    // free puzzles 2
    [
      [null, 3, null, null, null, 2, null, null, 9],
      [5, null, 9, null, null, null, null, null, null],
      [null, null, null, null, null, 8, null, null, 1],
      [3, null, 4, null, 9, null, null, 8, 5],
      [null, 7, null, 8, null, 3, null, 1, null],
      [8, 9, null, null, 6, null, 4, null, 7],
      [2, null, null, 3, null, null, null, null, null],
      [null, null, null, null, null, null, 1, null, 4],
      [1, null, null, 4, null, null, null, 2, null],
    ],
    // free puzzles 3
    [
      [null, 7, null, null, null, null, 6, null, null],
      [null, 6, null, 1, null, null, 4, 3, null],
      [null, null, null, null, 3, 5, null, 8, 7],
      [1, null, null, null, 6, null, null, 9, null],
      [null, 5, null, 4, null, 8, null, 7, null],
      [null, 8, null, null, 5, null, null, null, 4],
      [6, 3, null, 8, 1, null, null, null, null],
      [null, 1, 8, null, null, 2, null, 6, null],
      [null, null, 5, null, null, null, null, 4, null],
    ],
    // free puzzles 4
    [
      [3, 5, null, null, null, 1, 9, null, null],
      [null, null, null, null, null, null, 3, 5, 8],
      [null, null, 7, null, 2, null, 6, null, null],
      [null, 4, null, 1, null, null, null, null, null],
      [null, null, 9, null, 7, null, 4, null, null],
      [null, null, null, null, null, 2, null, 7, null],
      [null, null, 8, null, 1, null, 2, null, null],
      [5, 9, 1, null, null, null, null, null, null],
      [null, null, 3, 8, null, null, null, 6, 1],
    ],
    // free puzzles 5
    [
      [null, null, null, 7, null, null, 4, 8, null],
      [null, null, 2, 3, null, null, null, 9, null],
      [null, null, null, null, null, 9, null, null, 2],
      [null, null, null, null, null, 7, 6, 5, 9],
      [null, 6, null, null, 1, null, null, 3, null],
      [9, 5, 8, 6, null, null, null, null, null],
      [8, null, null, 5, null, null, null, null, null],
      [null, 4, null, null, null, 6, 1, null, null],
      [null, 7, 5, null, null, 1, null, null, null],
    ],
    // free puzzles 6
    [
      [null, null, null, null, null, 9, null, null, null],
      [null, 3, 9, null, 8, null, null, null, 7],
      [8, 4, null, 7, 6, null, null, null, null],
      [null, null, 7, 4, 9, null, null, null, 8],
      [3, null, 6, null, null, null, 2, null, 4],
      [4, null, null, null, 3, 2, 7, null, null],
      [null, null, null, null, 7, 4, null, 1, 5],
      [1, null, null, null, 2, null, 6, 4, null],
      [null, null, null, 5, null, null, null, null, null],
    ],
    // free puzzles 7
    [
      [9, null, null, 1, null, null, null, null, 3],
      [null, null, null, null, 8, 7, null, 6, 1],
      [null, 5, null, 2, null, null, null, null, null],
      [6, null, 4, null, null, 2, null, null, null],
      [3, null, null, null, 1, null, null, null, 7],
      [null, null, null, 4, null, null, 3, null, 2],
      [null, null, null, null, null, 3, null, 2, null],
      [2, 4, null, 9, 5, null, null, null, null],
      [8, null, null, null, null, 1, null, null, 4],
    ],
    // free puzzles 8
    [
      [null, 1, 7, null, null, null, null, null, 2],
      [9, null, null, null, 1, null, null, 6, null],
      [null, 2, null, null, null, 6, 9, null, 1],
      [null, 6, null, 9, 4, null, null, null, null],
      [null, null, 5, 6, null, 7, 4, null, null],
      [null, null, null, null, 3, 1, null, 9, null],
      [8, null, 9, 1, null, null, null, 3, null],
      [null, 3, null, null, 7, null, null, null, 9],
      [7, null, null, null, null, null, 1, 8, null],
    ],
    // free puzzles 9
    [
      [5, 2, null, 9, null, null, 6, null, 7],
      [null, null, 8, null, null, null, null, 9, null],
      [null, 9, null, 7, null, null, 3, null, null],
      [null, null, null, null, 8, null, 9, null, null],
      [8, null, null, 4, null, 6, null, null, 1],
      [null, null, 2, null, 7, null, null, null, null],
      [null, null, 5, null, null, 1, null, 3, null],
      [null, 3, null, null, null, null, 8, null, null],
      [4, null, 1, null, null, 3, null, 7, 9],
    ],
    // free puzzles 1null
  ],
  6: [
    [
      [null, 5, null, null, 6, null, null, null, null],
      [null, null, null, 2, 3, null, null, 1, null],
      [null, null, 1, null, null, null, 8, 2, null],
      [null, 8, 2, 4, null, null, null, null, null],
      [null, 7, null, null, 8, null, null, 3, null],
      [null, null, null, null, null, 7, 4, 5, null],
      [null, 2, 9, null, null, null, 1, null, null],
      [null, 1, null, null, 5, 6, null, null, null],
      [null, null, null, null, 4, null, null, 7, null],
    ],
    [
      [null, 5, null, null, 6, null, null, null, null],
      [null, null, null, 2, 3, null, null, 1, null],
      [null, null, 1, null, null, null, 8, 2, null],
      [null, 8, 2, 4, null, null, null, null, null],
      [null, 7, null, null, 8, null, null, 3, null],
      [null, null, null, null, null, 7, 4, 5, null],
      [null, 2, 9, null, null, null, 1, null, null],
      [null, 1, null, null, 5, 6, null, null, null],
      [null, null, null, null, 4, null, null, 7, null],
    ],
    [
      [4, null, null, null, 1, null, null, null, 8],
      [null, 9, null, null, null, null, null, null, 6],
      [null, 3, null, 7, 2, null, 4, null, null],
      [null, null, 3, null, 7, 1, null, null, null],
      [null, null, 4, 9, null, 8, 5, null, null],
      [null, null, null, 4, 5, null, 1, null, null],
      [null, null, 1, null, 6, 7, null, 8, null],
      [3, null, null, null, null, null, null, 7, null],
      [2, null, null, null, 4, null, null, null, 1],
    ],
    // free puzzles 1
    [
      [null, null, 1, null, null, 8, null, 7, 3],
      [null, null, 5, 6, null, null, null, null, 1],
      [7, null, null, null, null, 1, null, null, null],
      [null, 9, null, 8, 1, null, null, null, null],
      [5, 3, null, null, null, null, null, 4, 6],
      [null, null, null, null, 6, 5, null, 3, null],
      [null, null, null, 1, null, null, null, null, 4],
      [8, null, null, null, null, 9, 3, null, null],
      [9, 4, null, 5, null, null, 7, null, null],
    ],
    // free puzzles 2
    [
      [5, 9, null, null, null, 4, null, null, null],
      [null, 1, 6, null, 8, null, null, null, null],
      [null, 8, null, 1, null, null, null, null, 5],
      [3, null, null, null, null, null, 1, 4, null],
      [null, 6, 5, 4, null, 2, 7, 8, null],
      [null, 4, 8, null, null, null, null, null, 9],
      [9, null, null, null, null, 3, null, 5, null],
      [null, null, null, null, 4, null, 2, 3, null],
      [null, null, null, 8, null, null, null, 9, 7],
    ],
    // free puzzles 3
    [
      [null, null, null, 5, null, 9, null, null, null],
      [1, null, null, null, null, null, 7, null, null],
      [null, 5, null, null, 7, 2, null, null, 6],
      [7, 8, null, null, null, 6, 9, 3, null],
      [null, null, null, null, 4, null, null, null, null],
      [null, 2, 9, 7, null, null, null, 6, 5],
      [5, null, null, 8, 1, null, null, 4, null],
      [null, null, 4, null, null, null, null, null, 7],
      [null, null, null, 4, null, 3, null, null, null],
    ],
    // free puzzles 4
    [
      [2, null, null, null, 3, 5, 4, null, null],
      [5, null, 7, null, null, null, 1, null, null],
      [null, 4, null, null, null, 6, null, null, 8],
      [null, null, null, null, null, 4, null, 8, null],
      [null, 9, 3, null, 7, null, 5, 4, null],
      [null, 5, null, 9, null, null, null, null, null],
      [6, null, null, 3, null, null, null, 2, null],
      [null, null, 5, null, null, null, 3, null, 4],
      [null, null, 8, 4, 2, null, null, null, 5],
    ],
    // free puzzles 5
    [
      [null, null, null, 8, null, 3, 7, null, null],
      [null, 8, null, null, 1, null, null, null, null],
      [null, null, 4, null, null, null, 1, 2, null],
      [2, null, 8, null, null, null, null, 5, null],
      [5, null, null, 6, 9, 2, null, null, 1],
      [null, 9, null, null, null, null, 2, null, 4],
      [null, 7, 5, null, null, null, 8, null, null],
      [null, null, null, null, 8, null, null, 1, null],
      [null, null, 6, 3, null, 4, null, null, null],
    ],
    // free puzzles 6
    [
      [null, null, null, 2, null, 3, null, 6, null],
      [7, null, null, null, null, 5, 3, null, 1],
      [6, null, null, null, 7, null, null, 4, null],
      [null, 5, 3, null, null, null, null, null, null],
      [2, null, null, null, null, null, null, null, 8],
      [null, null, null, null, null, null, 1, 3, null],
      [null, 2, null, null, 9, null, null, null, 4],
      [8, null, 4, 1, null, null, null, null, 6],
      [null, 1, null, 6, null, 2, null, null, null],
    ],
    // free puzzles 7
    [
      [null, null, null, 2, null, null, 8, null, 1],
      [null, null, null, null, null, 7, null, null, null],
      [null, 1, 8, null, null, null, 3, 5, null],
      [5, null, 1, null, null, null, null, null, 9],
      [null, null, 6, null, 9, null, 5, null, null],
      [7, null, null, null, null, null, 4, null, 6],
      [null, 3, 4, null, null, null, 7, 9, null],
      [null, null, null, 7, null, null, null, null, null],
      [8, null, 7, null, null, 1, null, null, null],
    ],
    // free puzzles 8
    [
      [null, null, null, null, null, 2, null, null, 3],
      [null, null, null, null, null, 9, 6, null, null],
      [null, 9, null, 4, null, null, null, 2, 8],
      [null, 3, null, 7, null, 8, null, 6, 9],
      [null, null, 7, null, null, null, 8, null, null],
      [8, 1, null, 2, null, 3, null, 4, null],
      [1, 4, null, null, null, 6, null, 9, null],
      [null, null, 2, 1, null, null, null, null, null],
      [3, null, null, 5, null, null, null, null, null],
    ],
    // free puzzles 9
    [
      [null, 6, null, null, null, 4, null, null, 3],
      [4, null, null, null, 8, null, null, null, null],
      [3, null, 7, null, null, 5, 9, null, null],
      [null, 9, null, null, 1, null, null, null, 7],
      [null, null, 2, 5, null, 3, 6, null, null],
      [7, null, null, null, 4, null, null, 5, null],
      [null, null, 6, 4, null, null, 7, null, 1],
      [null, null, null, null, 2, null, null, null, 5],
      [5, null, null, 7, null, null, null, 2, null],
    ],
    // free puzzles 1null
    [
      [8, null, null, null, 5, null, 6, null, null],
      [5, null, null, 9, null, 3, 8, 1, null],
      [null, null, 1, null, null, null, null, 9, 7],
      [null, null, 2, 4, null, null, null, 3, null],
      [7, null, null, null, 2, null, null, null, 1],
      [null, 1, null, null, null, 8, 2, null, null],
      [1, 8, null, null, null, null, 3, null, null],
      [null, 6, 7, 8, null, 5, null, null, 9],
      [null, null, 3, null, 6, null, null, null, 5],
    ],
  ],
};
